language: objective-c
 
branches:
 only:
 - master
 
notifications:
 email:
  - bas@basbroek.nl
 on_success: always
 on_failure: always
 
xcode_project: SOP.xcodeproj
xcode_scheme: SOPTests
osx_image: xcode-7.2
xcode_sdk: iphonesimulator9.2
 
script:
- xcodebuild clean build -project code/SOP/SOP.xcodeproj -scheme SOPTests -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2'
