language: objective-c
 
branches:
 only:
 - master
 
xcode_project: SOP.xcodeproj
xcode_scheme: SOPTests
osx_image: xcode-7.2
xcode_sdk: iphonesimulator9.2
 
script:
- xcodebuild clean build -project code/SOP/SOP.xcodeproj -scheme SOPTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'
